#!/bin/sh
set -e
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_gconf
if [ "$1" = "configure" ]; then
	gconf-schemas --register renamer.schemas 
fi
# End automatically added section
